"use client"

import React from 'react'
import Image from "next/image";
import { MdElectricBolt } from "react-icons/md";

function Notification() {
    

    return(
        <>
           <section className='roles-section'>
                <div className='wrapper'>
                {/* row */}
                <artical className='roles-bottom-section'>
                    {/* head */}
                    <div className='roles-section-header'>
                    <h3 className='defaul-heading'>EMAIL PROCESSOR</h3>
                    </div>
                    <div className='stripe'>
                    <div className='stripe-radio'>
                        <label className="switch">
                        <input type="checkbox" />
                        <span className="slider"></span>
                        </label>

                        <span className='notification-connect'>Default WordPress Mailer</span>
                    </div>
                    <div id='stripe-connect'>

                        {/* <h4>Stripe Connect</h4> */}
                    </div>
                    </div>
                </artical>

                {/* row */}
                <artical className='roles-bottom-section'>
                    {/* head */}
                    <div className='roles-section-header'>
                    <h3 className='defaul-heading'>SMS PROCESSORS</h3>
                    </div>
                    <div className='stripe'>
                    <div className='stripe-radio'>
                        <label className="switch">
                        <input type="checkbox" />
                        <span className="slider"></span>
                        </label>

                        <img src="https://latepoint.appointmentstudio.com/wp-content/plugins/latepoint-sms-twilio/public/images/twilio.svg" alt="" />
                    </div>
                    <div id='stripe-connect'>

                        <h4>Twilio</h4>
                    </div>
                    </div>
                </artical>

                {/* row */}
                <artical className='roles-bottom-section'>
                    {/* head */}
                    <div className='roles-section-header'>
                    <h3 className='defaul-heading'>SMS PROCESSORS</h3>
                    </div>
                    <div className='stripe'>
                    <div className='stripe-radio'>
                        <label className="switch">
                        <input type="checkbox" />
                        <span className="slider"></span>
                        </label>

                        <img src="https://latepoint.appointmentstudio.com/wp-content/plugins/latepoint-sms-twilio/public/images/twilio.svg" alt="" />
                    </div>
                    <div id='stripe-connect'>

                        <h4>Whatsapp by Meta</h4>
                    </div>
                    </div>
                </artical>

                <artical className='other-bottom-section'>
                    {/* head */}
                    <div className='roles-section-header'>
                    <h3 className='defaul-heading'>OTHER SETTINGS</h3>
                    </div>
                    <div className='stripe'>
                    <div className='stripe-radio'>


                        <span className='notification-connect'>Default WordPress Mailer</span>
                    </div>
                    <div id='stripe-connect'>

                        {/* <h4>Stripe Connect</h4> */}
                    </div>
                    </div>
                </artical>

                <div>
                    <div className='admin-dropdown'>
                    <div className='admin-dropdown-flex'>
                        <div className='admin-dropdown-flex-left'>
                        <p>Email Layout</p>
                        </div>
                        <div className='admin-dropdown-flex-right'>
                        <p>This layout is used for your emails. You can customize it below and use variable to insert content of the email that is generated by the Process that was triggered. Go to Automation, Workflows to manage actual content of the email that is being sent.</p>
                        <button className='notification-show-layout-btn flex items-center'> <MdElectricBolt />Show layout variables</button>
                        </div>
                    </div>
                    </div>
                </div>

                <div>
                    <div className='admin-dropdown'>
                    <div className='admin-dropdown-flex'>
                        <div className='admin-dropdown-flex-left'>
                        <p>Password Reset</p>
                        </div>
                        <div className='admin-dropdown-flex-right'>
                        <p>This layout is used for your emails. You can customize it below and use variable to insert content of the email that is generated by the Process that was triggered. Go to Automation, Workflows to manage actual content of the email that is being sent.</p>
                        <button className='notification-show-layout-btn flex items-center'> <MdElectricBolt />Show layout variables</button>
                        </div>
                    </div>
                    </div>
                </div>



                <artical className='other-bottom-section'>
                    {/* head */}

                    <div className='chat-stripe'>
                    <div className='stripe-radio'>


                        <span className='notification-connect'>Chat Notifications</span>
                    </div>
                    <div id='stripe-connect'>

                        {/* <h4>Stripe Connect</h4> */}
                    </div>
                    </div>
                    <div>
                    <div className='admin-dropdown'>
                        <div className='admin-dropdown-flex'>
                        <div className='admin-dropdown-flex-left'>
                            <p>Settings</p>
                        </div>
                        <div className='admin-dropdown-flex-right'>
                            <div>
                            <div>
                                <input type="checkbox" id="" name="" value="" />
                                <span className='chat-notifications'>
                                Notify customers about new messages</span>
                            </div>
                            <div>
                                <input type="checkbox" id="" name="" value="" />
                                <span className='chat-notifications'>
                                Notify customers about new messages</span>
                            </div>
                            </div>

                        </div>

                        </div>
                    </div>
                    </div>

                </artical>
                <div className='notification-save-changes'>
                    <button>Save Channge</button>
                </div>

                </div>
           </section>
        </>
    );
}
export default Notification;