import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import ImportBsJS from "./components/ImportBs";

const inter = Inter({
  variable: "--font-inter-sans",
  weight: ['800','300','400','500', '700'],
  subsets: ['latin'],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <style>{`
          h1, h2, h3, h4, h5, button , a, input , p {
            font-family: ${inter.style.fontFamily};
          }
        
        `}
      </style>
      <ImportBsJS/>
        {children}
      </body>
    </html>
  );
}
